# Generated by Django 5.0.4 on 2024-08-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_ocrresult_delete_ocrdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrresult',
            name='image',
            field=models.ImageField(upload_to='ocr/images'),
        ),
    ]
